//HintName: Test_INS.Implementation.g.cs
// <auto-generated/>
#nullable enable
using EdiSource.Domain.Identifiers;
using EdiSource.Domain.Loop;
using EdiSource.Domain.Segments;
using EdiSource.Domain.SourceGeneration;
using EdiSource.Segments;
using EdiSource.Domain.Separator;
using EdiSource.Domain.Validation.SourceGeneration;
using EdiSource.Domain.Validation.Data;
using System.Linq;
using System.Collections.Generic;
using System;

namespace EdiSource.Loops
{
    public partial class Test_INS : Segment, IEdi<Test>, ISegmentIdentifier<Test_INS>
    {
        public Test_INS()
        {
            EdiId.CopyIdElementsToSegment(this);
        }

        public Test? Parent { get; set; }
        public static EdiId EdiId => new("INS", null);
    }
}