//HintName: TransactionSet.EdiElement.g.cs
// <auto-generated/>
#nullable enable
#nullable enable
using EdiSource.Domain.Separator;
using EdiSource.Domain.Segments;
using EdiSource.Domain.Identifiers;
using EdiSource.Domain.SourceGeneration;
using EdiSource.Domain.Loop;
using EdiSource.Domain.Validation.SourceGeneration;
using EdiSource.Domain.Validation.Data;
using System.Linq;
using System.Collections.Generic;
using System;

namespace Test
{
    public partial class TransactionSet
    {
        public List<IEdi?> EdiItems => new List<IEdi?>
        {
            ST,
            DTP,
            REFs,
            Loop2000,
            Loop2100s,
            SE,
            SE
        };
    }
}