//HintName: SegmentFooterAttribute.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // Unreferenced label
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS9113 // Parameter is unread.

namespace EdiSource.Domain.SourceGeneration;

/// <summary>
///     With a loop with the LoopGenerator attribute,
///     mark a loop with this attribute to enable source generation.
///     A segment footer is required and will be expected at the end.
///     For instance, an IEA is the footer of and ISA.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public sealed class SegmentFooterAttribute : Attribute;