//HintName: SegmentHeaderAttribute.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // Unreferenced label
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS9113 // Parameter is unread.

namespace EdiSource.Domain.SourceGeneration;

/// <summary>
///     With a loop with the LoopGenerator attribute,
///     mark a segment header with this attribute to enable source generation.
///     A segment header is required and is expected to begin a loop.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public sealed class SegmentHeaderAttribute : Attribute;