global using EdiSource.Domain;
global using EdiSource.Domain.Standard.Loops;
global using EdiSource.Domain.Standard.Loops.ISA;
global using EdiSource.Domain.Standard.Segments;
global using EdiSource.Domain.Validation.Data;
global using EdiSource.Domain.Segments.Extensions;
global using EdiSource.Domain.SourceGeneration;
global using EdiSource.Domain.Validation.SourceGeneration;
global using EdiSource.Domain.Validation.Factory;
global using EdiSource.Domain.Loop;
global using EdiSource.Domain.Segments;
global using EdiSource.Domain.Helper;
global using static EdiSource.Domain.Identifiers.EdiId;