//HintName: LoopGeneratorAttribute.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // Unreferenced label
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS9113 // Parameter is unread.

using EdiSource.Domain.Identifiers;
using EdiSource.Domain.Loop;
using EdiSource.Domain.Segments;

namespace EdiSource.Domain.SourceGeneration;

/// <summary>
///     Enables source generation to occur on a loop.
///     Generics are needed for the source generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class LoopGeneratorAttribute<TParent, TSelf, TId>(bool isTransactionSet = false) : Attribute
#pragma warning restore CS9113 // Parameter is unread.
    where TParent : ILoop
    where TSelf : ILoop
    where TId : Segment, IEdi<TSelf>, ISegmentIdentifier<TId>;