//HintName: SegmentGeneratorAttributes.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // Unreferenced label
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS9113 // Parameter is unread.

using EdiSource.Domain.Loop;
using EdiSource.Domain.Segments;

namespace EdiSource.Domain.SourceGeneration;
#pragma warning disable CS9113 // Parameter is unread.

/// <summary>
///     Mark a segment class with this attribute to enable source generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class SegmentGenerator<TParent>(params string?[] args) : Attribute
    where TParent : ILoop;

public sealed class SegmentGenerator<TParent, TBase>(params string[] args) : Attribute
    where TParent : ILoop
    where TBase : Segment;