global using EdiSource.Domain;
global using EdiSource.Domain.Standard.Loops;
global using EdiSource.Domain.Standard.Loops.ISA;
global using EdiSource.Domain.Standard.Segments;
global using EdiSource.Domain.Validation.Data;
global using _834 = EdiSource.SampleApp.Loops._834;
global using Loop2000 = EdiSource.SampleApp.Loops.Loop2000;
global using Loop2000_DTP = EdiSource.SampleApp.Segments.Loop2000_DTP;
global using Loop2000_INS = EdiSource.SampleApp.Segments.Loop2000_INS;
global using Loop2000_REF = EdiSource.SampleApp.Segments.Loop2000_REF;
global using Loop2100 = EdiSource.SampleApp.Loops.Loop2100;
global using Loop2100_DMG = EdiSource.SampleApp.Segments.Loop2100_DMG;
global using Loop2100_N3 = EdiSource.SampleApp.Segments.Loop2100_N3;
global using Loop2100_N4 = EdiSource.SampleApp.Segments.Loop2100_N4;
global using Loop2100_NM1 = EdiSource.SampleApp.Segments.Loop2100_NM1;
global using Loop2100_PER = EdiSource.SampleApp.Segments.Loop2100_PER;
global using TS_DTP = EdiSource.SampleApp.Segments.TS_DTP;
global using TS_REF = EdiSource.SampleApp.Segments.TS_REF;
global using TS_SE = EdiSource.SampleApp.Segments.TS_SE;
global using TS_ST = EdiSource.SampleApp.Segments.TS_ST;
global using EdiSource.Domain.Segments.Extensions;
global using EdiSource.Domain.SourceGeneration;
global using EdiSource.Domain.Validation.SourceGeneration;
global using EdiSource.Domain.Validation.Factory;
global using EdiSource.Domain.Loop;
global using EdiSource.Domain.Segments;